# Generated by Django 5.0.2 on 2024-02-22 18:12

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_image_created_alter_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان اپدیت'),
        ),
    ]
